# Permalinks
#
permalink:           pretty

# Setup
title:               Design _ Hover
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 www.designhover.xyz
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Henry Lo
  url:               https://twitter.com/fiveonethree
  email:             henri.hwlo@gmail.com

# Custom vars
version:             1.0.0
