# Permalinks
#
permalink:           pretty

# Setup
title:               Design _ Hover
tagline:             'A simple blog'
description:         'Just a dude typing on his chromebook and publishing to the internet'
url:                 www.designhover.xyz
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Henry Lo
  url:               https://twitter.com/fiveonethree
  email:             henri.hwlo@gmail.com

# Custom vars
version:             1.0.0
